version: "3.9"
services:

  spring-api-image:
    # image: nk-recipes-api:latest
    image: yan640/nk-recipes-api:lastest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: nk-spring-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - spring-network
    depends_on:
      - mysql
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_recipes_api
    #   - SPRING_DATASOURCE_USERNAME=nk-yannick
    #   - SPRING_DATASOURCE_PASSWORD=101010

  mysql:
    image: mysql
    container_name: nk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_recipes_api
      MYSQL_USER: nk-yannick
      MYSQL_PASSWORD: 101010
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init-db-scripts:/docker-entrypoint-initdb.d # fix exec init.sql

networks:
  spring-network:
    driver: bridge

volumes:
  mysql-volume: